name: Update RSS Feeds

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:     # allow manual trigger

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate_rss.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.xml
          git commit -m "Update RSS feeds" || echo "No changes"
          git push
